apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifacts-pv-dev
  namespace: smart-dc-dev
  labels:
    type: azurefile
    environment: dev
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: dev-preprocessed-artifacts
    readOnly: false
  mountOptions:
    - vers=3.0
    - dir_mode=0777
    - file_mode=0777
    - serverino
