apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifacts-pv-$ENVIRONMENT
  namespace: $NAMESPACE
  labels:
    type: azurefile
    environment: $ENVIRONMENT
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: $FILESHARE_NAME
    readOnly: false
  mountOptions:
    - vers=3.0
    - dir_mode=0777
    - file_mode=0777
    - serverino
