services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    restart: always
    ports:
      - "5006:5006"   # access MLflow UI on localhost:5006
    environment:
      BACKEND_STORE_URI: postgresql://citus:passwordY@host:5432/citus?options=-csearch_path=mlflow
      ARTIFACT_ROOT: /mlflow/artifacts
    command: /bin/bash -c "\
      pip install psycopg2-binary sqlalchemy && \
      mlflow server \
        --backend-store-uri $BACKEND_STORE_URI \
        --default-artifact-root $ARTIFACT_ROOT \
        --host 0.0.0.0 \
        --port 5006"
    volumes:
      - mlruns:/mlflow/artifacts

volumes:
  mlruns:
