version: '3.8'

services:
  # PostgreSQL database for metadata
  postgres:
    image: postgres:13
    container_name: mlflow_postgres
    environment:
      POSTGRES_DB: citus
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mlflow_network

  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./mlflow_artifacts:/opt/mlflow/artifacts
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow_user:mlflow_pass@postgres:5432/mlflow
    networks:
      - mlflow_network
    command: >
      mlflow server 
      --backend-store-uri postgresql://mlflow_user:mlflow_pass@postgres:5432/mlflow
      --default-artifact-root file:///opt/mlflow/artifacts 
      --host 0.0.0.0 
      --port 5000

networks:
  mlflow_network:
    driver: bridge

volumes:
  postgres_data:
  mlflow_artifacts: