# MLflow Dev Environment Configuration
ENVIRONMENT: dev
NAMESPACE: smart-dc-dev
MLFLOW_IMAGE: aimlsgkdchregistrydev.azurecr.io/smart-dc-mlflow:v3.3.2
PORT: 8000
DEBUG: False
LOG_LEVEL: WARNING

# Access Configuration - Use ClusterIP with Ingress
SERVICE_TYPE: ClusterIP
MLFLOW_PATH: /mlflowdev

# PostgreSQL Configuration
PG_USER: <fill in the username>
PG_PASSWORD: <fill in the password>
PG_HOST: c.kdch-sg-aiml-postgresql-dev-02.postgres.database.azure.com
PG_DATABASE: citus
PG_PORT: 5432
PG_SCHEMA: mlflow

# Azure File Share Configuration
FILESHARE_NAME: dev-preprocessed-artifacts
