apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifacts-pv-prod
  namespace: smart-dc-prod
  labels:
    type: azurefile
    environment: prod
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: prod-preprocessed-artefacts
    readOnly: false
  mountOptions:
    - vers=3.0
    - dir_mode=0777
    - file_mode=0777
    - serverino
